### PR TITLE
Add support for select_library_configurations

### PR DESCRIPTION
**Pull request by mloskot**
Ports a very useful patch from Vcpkg: https://github.com/microsoft/vcpkg/blob/b286cd50ddefb3d9457e261bf6518b1a46f4a830/ports/libraw/findlibraw_debug_fix.patch

Sets CMAKE_DEBUG_POSTFIX with "d" as default for WIN32.

### References

On uses of `CMAKE_DEBUG_POSTFIX`: 

   - https://github.com/curl/curl/issues/2121#issuecomment-374253607
   - https://github.com/curl/curl/pull/2384#discussion_r175475801

### CODE REVIEW

**Comment by letmaik** [comment]
Can you describe what this does? I haven't seen that before.

**Comment by mloskot** [comment]
Sure, but I'mnnit sure what more I could add to the CMake docs whereiit's explained quite well https://cmake.org/cmake/help/latest/module/SelectLibraryConfigurations.html

Let me know what kind of info you're missing

**Comment by letmaik** [comment]
In essence, you want the FindLibRaw module to search for debug variants as well, named `rawd` and `raw_rd`, and expose this as new `LibRaw_LIBRARY_DEBUG`, `LibRaw_LIBRARY_RELEASE` etc variables, keeping the original ones like `LibRaw_LIBRARY` more or less as they are but let them prefer the RELEASE variant (if found) over the DEBUG variant.

I'm missing some motivation for this change. The CMake scripts don't build `rawd` or `raw_rd` named variants, which makes your FindLibRaw.cmake changes a bit confusing and out of place. Can you explain this a bit more?

**Comment by mloskot** [comment]
> The CMake scripts don't build rawd or raw_rd named variants,
> which makes your FindLibRaw.cmake changes a bit confusing and out of place.
> Can you explain this a bit more?

I'd argue the statement "CMake scripts don't build rawd or raw_rd" is not quite accurate, because this particular behaviour does not depend on the declared CMake configuration, but on CMake execution. I'll try to explain.

On Windows, optimized and debug builds are 'incompatible' enough and, for optimal workflow, users of a library need both builds. It is common to deploy both, optimized and debug, builds of a library into common `{prefix}/{bin,include,lib}` location(s). Since it means there is potential for naming clash, CMake offers tools to avoid it, namely [CMAKE_DEBUG_POSTFIX](https://cmake.org/cmake/help/latest/variable/CMAKE_DEBUG_POSTFIX.html?highlight=cmake_debug_postfix).

Please, consider the complete build workflow below which is quite common to Windows + MSVC environment. Here, I'm using Visual Studio 2019 and CMake 3.14, executing all commands in the `x64 Native Tools Command Prompt for VS 2019`:

```
D:\> git clone https://github.com/LibRaw/LibRaw.git
D:\> git clone https://github.com/LibRaw/LibRaw-cmake.git
D:\> mkdir LibRaw\cmake
D:\> xcopy LibRaw-cmake\CMakeLists.txt LibRaw\ /Y /F
D:\> xcopy LibRaw-cmake\cmake\* LibRaw\cmake\ /E /Y /F
```

```
D:\> set CL=/DWIN32=1
D:\> cd LibRaw
```

```
D:\LibRaw> cmake -S . -B _build_vs2019_opt -G Ninja -DCMAKE_INSTALL_PREFIX=%CD%/_install -DCMAKE_BUILD_TYPE=Release
D:\LibRaw> cmake --build _build_vs2019_opt -j 4 --verbose

D:\LibRaw> cmake -S . -B _build_vs2019_dbg -G Ninja -DCMAKE_INSTALL_PREFIX=%CD%/_install -DCMAKE_BUILD_TYPE=Debug -DCMAKE_DEBUG_POSTFIX=d
D:\LibRaw> cmake --build _build_vs2019_dbg -j 4 --verbose
```

```
D:\LibRaw> cmake --build _build_vs2019_opt --target install
[0/1] Install the project...
-- Install configuration: "Release"
-- Installing: D:/LibRaw/_install/include/libraw/libraw.h
-- Installing: D:/LibRaw/_install/include/libraw/libraw_alloc.h
-- Installing: D:/LibRaw/_install/include/libraw/libraw_const.h
-- Installing: D:/LibRaw/_install/include/libraw/libraw_datastream.h
-- Installing: D:/LibRaw/_install/include/libraw/libraw_internal.h
-- Installing: D:/LibRaw/_install/include/libraw/libraw_types.h
-- Installing: D:/LibRaw/_install/include/libraw/libraw_version.h
-- Installing: D:/LibRaw/_install/include/libraw/libraw_config.h
-- Installing: D:/LibRaw/_install/lib/raw.lib
-- Installing: D:/LibRaw/_install/bin/raw.dll
-- Installing: D:/LibRaw/_install/lib/raw_r.lib
-- Installing: D:/LibRaw/_install/bin/raw_r.dll
...
```

```
D:\LibRaw> cmake --build _build_vs2019_dbg --target install
-- Install configuration: "Debug"
-- Up-to-date: D:/LibRaw/_install/include/libraw/libraw.h
-- Up-to-date: D:/LibRaw/_install/include/libraw/libraw_alloc.h
-- Up-to-date: D:/LibRaw/_install/include/libraw/libraw_const.h
-- Up-to-date: D:/LibRaw/_install/include/libraw/libraw_datastream.h
-- Up-to-date: D:/LibRaw/_install/include/libraw/libraw_internal.h
-- Up-to-date: D:/LibRaw/_install/include/libraw/libraw_types.h
-- Up-to-date: D:/LibRaw/_install/include/libraw/libraw_version.h
-- Installing: D:/LibRaw/_install/include/libraw/libraw_config.h
-- Installing: D:/LibRaw/_install/lib/rawd.lib
-- Installing: D:/LibRaw/_install/bin/rawd.dll
-- Installing: D:/LibRaw/_install/lib/raw_rd.lib
-- Installing: D:/LibRaw/_install/bin/raw_rd.dll
...
```

This technique is used by package managers which deploy both types of builds, for example, Vcpkg (see [libraw/portfile.cmake](https://github.com/microsoft/vcpkg/blob/b286cd50ddefb3d9457e261bf6518b1a46f4a830/ports/libraw/portfile.cmake#L37)).

**Comment by letmaik** [comment]
Thanks, that helped. To make this PR complete, why not additionally set `CMAKE_DEBUG_POSTFIX` if it's not specified? Then there would be a direct relation to the naming in the Find* script. See Brad King's comment at https://github.com/curl/curl/issues/2121#issuecomment-374253607.

**Comment by letmaik** [comment]
Regarding your reference to vcpkg, I was under the impression that vcpkg installs debug libraries in a separate folder tree anyway, which then is correctly selected when using the vcpkg CMake toolchain file. Is that incorrect? If not, how can there be naming conflicts?

**Comment by mloskot** [comment]
> To make this PR complete, why not additionally set CMAKE_DEBUG_POSTFIX if it's not specified?

Good point. Brad's comment make sense. I will update this PR.

> Regarding your reference to vcpkg, I was under the impression that vcpkg installs debug libraries
> in a separate folder tree anyway (...)

This is correct. I was pointing at Vcpkg as example where it is used, but not necessarily for all the reasons I presented. AFAIS, Vcpkg still seem to follow the `CMAKE_DEBUG_POSTFIX` convention across the ports.
Possibly, it's to avoid potential problems when DLLs of run-time dependencies are copied as per https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md

> a post-build action for executable projects that will analyze and copy any DLLs you need to the output folder, enabling a seamless F5 experience.

**Comment by letmaik** [comment]
What about this part?
https://github.com/LibRaw/LibRaw-cmake/blob/d4e130ac0e50cbde07a956711e3e7ad55a129b08/CMakeLists.txt#L582-L591

https://github.com/LibRaw/LibRaw-cmake/blob/c8a802885e838381a7531ea0e555b9b42c8622e5/cmake/data/libraw.pc.cmake#L11

If you have `d` as suffix then these files won't work anymore if pkgconfig is used. I'm not sure how this is handled in general, i.e. whether there is typically only a single pkgconfig file for release mode, or whether there should be a debug variant as well in that case. Either way, wouldn't it be a breaking change in some cases?

**Comment by mloskot** [comment]
I was concerned about that and I'd be more comfortable with least intrusive change like this:

```
IF(WIN32 AND NOT DEFINED CMAKE_DEBUG_POSTFIX)  # or even IF(MSVC ...
    SET(CMAKE_DEBUG_POSTFIX "d")
ENDIF()
```

I just could not find any OS-specific recommendations regarding use of `CMAKE_DEBUG_POSTFIX`.

Shall I enable `SET(CMAKE_DEBUG_POSTFIX "d")` for MSVC or WIN32 only?

**Comment by letmaik** [comment]
OK, let's do it for Windows only to avoid any potential issues. I think WIN32 is fine.

**Comment by mloskot** [comment]
I updated the PR setting the postfix for WIN32 only.

**Comment by letmaik** [comment]
Thanks again for this and for your patience! Future PRs always welcome :)

**Comment by mloskot** [comment]
I'm happy to help. Thanks for merging.

**Pull request merged**
