### PR TITLE
Travis CI: Update environment, use GCC 10 & add Arm64 job

### PR DESCRIPTION
**Pull request by EwoutH**
- Updates the build environment to Ubuntu 18.04 Bionic
 - Uses GCC 10
 - Adds Arm64 job (that runs on ARMv8 hardware)

### CODE REVIEW

**Comment by EwoutH** [comment]
@LibRaw Travis CI recently migrated from travis-ci.org to travis-ci.com. Could you login on [travis-ci.com](https://travis-ci.com/) with GitHub and enable Travis CI for LibRaw-cmake?

@letmaik This run passes on https://travis-ci.org/github/LibRaw/LibRaw-cmake, could you please review?

**Comment by letmaik** [comment]
@EwoutH What's the motivation for using GCC 10?

**Comment by EwoutH** [comment]
Thanks for the quick response! It's the newest stable version in the GCC releases, so it supports modern CPUs and SIMD instructions, and performs [a bit better](https://www.phoronix.com/scan.php?page=article&item=gcc5-gcc10-benchmarks&num=4) then earlier GCC versions. It's also [stricter](https://gcc.gnu.org/gcc-10/porting_to.html) in some ways, providing earlier warnings about code conventions.

**Review by letmaik — APPROVED** [review]

**Comment by letmaik** [comment]
I'm holding off with merging until @LibRaw has enabled travis-ci.com here.

**Comment by letmaik** [comment]
@EwoutH There were other PRs in the meantime which did trigger CI correctly, so I assume it's working (again?), even though it is still on travis-ci.org. Could you push an empty commit to trigger CI? Also, would you mind removing GCC 10 again? The CI in this repo is only for testing the CMake scripts, not for testing libraw (this should happen in the main repo).

**Comment by letmaik** [comment]
CI is based on GitHub Actions now. If you're still interested in this please open a new PR.

**Pull request closed without merging**
